---
- name: Install and Configure Kubernetes Master
  hosts: myhosts
  become: yes
  become_method: sudo
  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present

    - name: add Kubernetes apt-key
      apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present

    - name: Add Kubernetes APT repository
      apt_repository:
        repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
        state: present
        filename: 'kubernetes'

    - name: Update apt package cache (again)
      apt:
        update_cache: yes

    - name: install kubeadm
      apt:
        name: kubeadm
        state: present
        update_cache: true

    - name: install kubelet
      apt:
        name: kubelet
        state: present
        update_cache: true

    - name: install kubectl
      apt:
        name: kubelet
        state: present
        update_cache: true

